apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab-infrastructure
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://github.com/dustingolding/homelab-infrastructure
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab-infrastructure
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./clusters/k3s-homelab
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-infrastructure
  wait: true
  timeout: 5m0s
