apiVersion: batch/v1
kind: CronJob
metadata:
  generation: 2
  name: mariadb-backup
  namespace: cms
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata: {}
    spec:
      template:
        metadata: {}
        spec:
          containers:
          - command:
            - /bin/bash
            - -ec
            - "TS=$(date +%F_%H%M)\nOUTDIR=/backups/db\nmkdir -p \"${OUTDIR}\"\nmariadb-dump\
              \ -h \"${DB_HOST}\" -u \"${DB_USER}\" -p\"${DB_PASS}\" \"${DB_NAME}\"\
              \ \\\n  | gzip > \"${OUTDIR}/wordpress_${TS}.sql.gz\"\nfind \"${OUTDIR}\"\
              \ -type f -mtime +14 -name \"*.sql.gz\" -delete\n"
            env:
            - name: DB_HOST
              value: mariadb.cms.svc.cluster.local
            - name: DB_NAME
              value: wordpress
            - name: DB_USER
              value: dustin
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: mariadb-password
                  name: mariadb
            image: bitnami/mariadb:latest
            imagePullPolicy: IfNotPresent
            name: mariadb-backup
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /backups
              name: backups
          dnsPolicy: ClusterFirst
          nodeSelector:
            kubernetes.io/hostname: k3s-w3
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - name: backups
            persistentVolumeClaim:
              claimName: cms-backups-pvc
  schedule: 0 2 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
