apiVersion: batch/v1
kind: CronJob
metadata:
  generation: 1
  name: mariadb-restore-test
  namespace: cms
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata: {}
    spec:
      backoffLimit: 0
      template:
        metadata: {}
        spec:
          containers:
          - command:
            - /bin/bash
            - -ec
            - "latest_file=$(ls -t /backups/db/*.sql.gz | head -n 1)\nif [ -z \"$latest_file\"\
              \ ]; then\n  echo \"No backup files found in /backups/db\" >&2\n  exit\
              \ 1\nfi\necho \"Using backup: $latest_file\"\n\nmariadb -h mariadb.cms.svc.cluster.local\
              \ -u root -p\"$MARIADB_ROOT_PASSWORD\" -e \"DROP DATABASE IF EXISTS\
              \ wordpress_restore_test; CREATE DATABASE wordpress_restore_test;\"\n\
              gunzip -c \"$latest_file\" | mariadb -h mariadb.cms.svc.cluster.local\
              \ -u root -p\"$MARIADB_ROOT_PASSWORD\" wordpress_restore_test\n\nmariadb\
              \ -h mariadb.cms.svc.cluster.local -u root -p\"$MARIADB_ROOT_PASSWORD\"\
              \ -e \"SELECT COUNT(*) AS tables_count FROM information_schema.tables\
              \ WHERE table_schema='wordpress_restore_test';\"\nmariadb -h mariadb.cms.svc.cluster.local\
              \ -u root -p\"$MARIADB_ROOT_PASSWORD\" -e \"DROP DATABASE IF EXISTS\
              \ wordpress_restore_test;\"\n"
            env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mariadb-root-password
                  name: mariadb
            image: bitnami/mariadb:latest
            imagePullPolicy: IfNotPresent
            name: restore-test
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /backups
              name: backups
          dnsPolicy: ClusterFirst
          nodeSelector:
            kubernetes.io/hostname: k3s-w3
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - name: backups
            persistentVolumeClaim:
              claimName: cms-backups-pvc
  schedule: 30 3 * * 0
  successfulJobsHistoryLimit: 1
  suspend: false
