apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"batch/v1","kind":"CronJob","metadata":{"annotations":{},"name":"mariadb-backup","namespace":"cms"},"spec":{"failedJobsHistoryLimit":3,"jobTemplate":{"spec":{"template":{"spec":{"containers":[{"command":["/bin/bash","-ec","TS=$(date
      +%F_%H%M)\nOUTDIR=/backups/db\nmkdir -p \"${OUTDIR}\"\nmariadb-dump -h \"${DB_HOST}\"
      -u \"${DB_USER}\" -p\"${DB_PASS}\" \"${DB_NAME}\" \\\n  | gzip \u003e \"${OUTDIR}/wordpress_${TS}.sql.gz\"\nfind
      \"${OUTDIR}\" -type f -mtime +14 -name \"*.sql.gz\" -delete\n"],"env":[{"name":"DB_HOST","value":"mariadb.cms.svc.cluster.local"},{"name":"DB_NAME","value":"wordpress"},{"name":"DB_USER","value":"dustin"},{"name":"DB_PASS","valueFrom":{"secretKeyRef":{"key":"mariadb-password","name":"mariadb"}}}],"image":"bitnami/mariadb:latest","name":"mariadb-backup","volumeMounts":[{"mountPath":"/backups","name":"backups"}]}],"nodeSelector":{"kubernetes.io/hostname":"k3s-w3"},"restartPolicy":"OnFailure","volumes":[{"name":"backups","persistentVolumeClaim":{"claimName":"cms-backups-pvc"}}]}}}},"schedule":"0
      2 * * *","successfulJobsHistoryLimit":3}}

      '
  creationTimestamp: '2026-02-07T05:19:24Z'
  generation: 2
  name: mariadb-backup
  namespace: cms
  resourceVersion: '313058'
  uid: d5eb7942-37f8-49ee-a378-99ab2edbe3d6
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata: {}
    spec:
      template:
        metadata: {}
        spec:
          containers:
          - command:
            - /bin/bash
            - -ec
            - "TS=$(date +%F_%H%M)\nOUTDIR=/backups/db\nmkdir -p \"${OUTDIR}\"\nmariadb-dump\
              \ -h \"${DB_HOST}\" -u \"${DB_USER}\" -p\"${DB_PASS}\" \"${DB_NAME}\"\
              \ \\\n  | gzip > \"${OUTDIR}/wordpress_${TS}.sql.gz\"\nfind \"${OUTDIR}\"\
              \ -type f -mtime +14 -name \"*.sql.gz\" -delete\n"
            env:
            - name: DB_HOST
              value: mariadb.cms.svc.cluster.local
            - name: DB_NAME
              value: wordpress
            - name: DB_USER
              value: dustin
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: mariadb-password
                  name: mariadb
            image: bitnami/mariadb:latest
            imagePullPolicy: IfNotPresent
            name: mariadb-backup
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /backups
              name: backups
          dnsPolicy: ClusterFirst
          nodeSelector:
            kubernetes.io/hostname: k3s-w3
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - name: backups
            persistentVolumeClaim:
              claimName: cms-backups-pvc
  schedule: 0 2 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
status:
  lastScheduleTime: '2026-02-09T02:00:00Z'
  lastSuccessfulTime: '2026-02-09T02:00:04Z'
