apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: cms
spec:
  interval: 10m
  dependsOn:
    - name: mariadb
      namespace: cms
    - name: redis
      namespace: cms
  chart:
    spec:
      chart: wordpress
      version: 28.1.5
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    createNamespace: true
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: cms-wordpress-values
      valuesKey: values.yaml
