apiVersion: v1
kind: Secret
metadata:
    name: wordpress
    namespace: cms
type: Opaque
stringData:
    wordpress-username: ENC[AES256_GCM,data:MrdQWKFFflB+qA==,iv:CDES1Gxj0xFiZWhYUhitag/ljMFX2PF7kpbSmLvoKVI=,tag:8/hdN1wZVP7ptRzDRlqi4w==,type:str]
    wordpress-password: ENC[AES256_GCM,data:2Vozi1dVfxGMVQ==,iv:D1scgHUNZ0U2LRS8F8bhcu+xUVKjGB/tV7lb/qflzRs=,tag:jKKHdgooZXbKgjCtMLDiOg==,type:str]
    redis-password: ENC[AES256_GCM,data:KOxsqY1Y2cH4BQ==,iv:toICaznDimVZ8pNU3EQOu4R2rgufoW0WYrIjWMEfpVg=,tag:PqV3W7muPAfCDWYrV4Urhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r2un9h6vv43hqd089mfaxks90z4s30hakru54pfsdctclnppwdhs53g6ar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVldMYytGOXdDSXRHTlFy
            d09rMWRBNWxJT2FUN1VvRG03ZHpJWjRwTFNFCmh6dHUyWXU0Q1YzNXJ3aUhQWDF0
            NEFEU0xlV045TFh6OUlJbUU3TjluemsKLS0tIGhxYkxxRmsxTUVVUjQwU21kSTNu
            TlJSZGN4dHl6NnRORncvYmRMajNPYjQKE+5TcKskOcgGBMTEDzFcl3VOcR7WsgQR
            zOby5js3srPPdpdkSVHmf+4NMTYRJ2cskD//YjcLFnw3WI0y2qKzKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T21:36:53Z"
    mac: ENC[AES256_GCM,data:CVhSp82P1wDrFHKnYZYXvHxqX3qlCqG1rctGLIv+75ikUGPe40Qik7MEF7rb0B7miWC+jsw3XCCpCjilKdonJsiqGXQztOlcBKFRG3hoKBzq8OcufB561X7BWq+1xy8heRtJSvKg+m8uTnfkEhiulNe3uUee87qhDTJDDu1grrw=,iv:YFLG3CrIcLXMyyPoI1I7TOdXnTi4UwuxI0DLfRXS4U4=,tag:H5WpfPeHK3wiQ478QvPOSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
