apiVersion: batch/v1
kind: CronJob
metadata:
  generation: 3
  name: wordpress-backup
  namespace: cms
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata: {}
    spec:
      template:
        metadata: {}
        spec:
          containers:
          - command:
            - /bin/sh
            - -ec
            - 'TS=$(date +%F_%H%M)

              OUTDIR=/backups/wp

              mkdir -p "${OUTDIR}"

              tar -czf "${OUTDIR}/wp-content_${TS}.tar.gz" -C /source wp-content

              find "${OUTDIR}" -type f -mtime +14 -name "*.tar.gz" -delete

              '
            image: alpine:3.20
            imagePullPolicy: IfNotPresent
            name: wordpress-backup
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /source
              name: wordpress-data
              readOnly: true
              subPath: wordpress
            - mountPath: /backups
              name: backups
          dnsPolicy: ClusterFirst
          nodeSelector:
            kubernetes.io/hostname: k3s-w1
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - name: wordpress-data
            persistentVolumeClaim:
              claimName: wordpress
          - name: backups
            persistentVolumeClaim:
              claimName: cms-backups-wp-pvc
  schedule: 15 2 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
