apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"batch/v1","kind":"CronJob","metadata":{"annotations":{},"name":"wp-cron","namespace":"cms"},"spec":{"jobTemplate":{"spec":{"template":{"spec":{"containers":[{"args":["/bin/sh","-ec","curl
      -fsS https://cms.thealgoera.com/wp-cron.php?doing_wp_cron \u003e /dev/null\n"],"image":"curlimages/curl:8.7.1","name":"wp-cron"}],"restartPolicy":"OnFailure"}}}},"schedule":"*/5
      * * * *"}}

      '
  creationTimestamp: '2026-02-07T04:48:48Z'
  generation: 2
  name: wp-cron
  namespace: cms
  resourceVersion: '313047'
  uid: 007a37d0-b0cb-4c76-b22e-f4eb3c87af28
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata: {}
    spec:
      template:
        metadata: {}
        spec:
          containers:
          - args:
            - /bin/sh
            - -ec
            - curl -fsS http://wordpress.cms.svc.cluster.local/wp-cron.php?doing_wp_cron
              > /dev/null
            image: curlimages/curl:8.7.1
            imagePullPolicy: IfNotPresent
            name: wp-cron
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '*/5 * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
status:
  lastScheduleTime: '2026-02-09T02:00:00Z'
  lastSuccessfulTime: '2026-02-09T02:00:03Z'
