apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: '18'
  generation: 18
  name: alloy
  namespace: observability
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2026-02-06T04:44:12Z'
      labels:
        app: alloy
    spec:
      containers:
      - args:
        - run
        - /etc/alloy/alloy-config.yaml
        image: grafana/alloy:latest
        imagePullPolicy: Always
        name: alloy
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/alloy
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: alloy
      serviceAccountName: alloy
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: alloy-config
        name: config
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
