apiVersion: v1
kind: Pod
metadata:
  name: bind-wp-backups
  namespace: cms
spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: k3s-w1
  containers:
  - name: bind
    image: alpine:3.20
    command:
    - /bin/sh
    - -ec
    - sleep 10
    volumeMounts:
    - name: backups
      mountPath: /backups
  volumes:
  - name: backups
    persistentVolumeClaim:
      claimName: cms-backups-wp-pvc
