apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cms-backups-pvc
  namespace: cms
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
