apiVersion: v1
kind: Pod
metadata:
  name: list-db-backups
  namespace: cms
spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: k3s-w3
  containers:
  - name: list
    image: alpine:3.20
    command:
    - /bin/sh
    - -ec
    - ls -la /backups && ls -la /backups/db || true
    volumeMounts:
    - name: backups
      mountPath: /backups
  volumes:
  - name: backups
    persistentVolumeClaim:
      claimName: cms-backups-pvc
