apiVersion: batch/v1
kind: CronJob
metadata:
  name: wp-cron
  namespace: cms
spec:
  schedule: '*/5 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: wp-cron
            image: curlimages/curl:8.7.1
            args:
            - /bin/sh
            - -ec
            - 'curl -fsS https://cms.thealgoera.com/wp-cron.php?doing_wp_cron > /dev/null

              '
