apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/instance: alloy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: alloy
    app.kubernetes.io/part-of: alloy
    app.kubernetes.io/version: v1.12.2
    helm.sh/chart: alloy-1.5.3
  name: alloy
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - pods/log
  - namespaces
  verbs:
  - get
  - list
  - watch
