apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alloy-log-reader
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - pods/log
  - nodes
  - namespaces
  verbs:
  - get
  - list
  - watch
