apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    objectset.rio.cattle.io/hash: 6907b6d8deee71490cc29394fcd77ae2feeee248
  name: clustercidrs-node
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - clustercidrs
  verbs:
  - list
  - watch
