apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    objectset.rio.cattle.io/hash: 5089468545c5482413c7f05e837e9b88f02ad052
  name: k3s-cloud-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k3s-cloud-controller-manager
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: k3s-cloud-controller-manager
  namespace: kube-system
