apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:service-cidrs-controller
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - servicecidrs
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - servicecidrs/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - servicecidrs/status
  verbs:
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ipaddresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
  - update
