apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:resource-claim-controller
rules:
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - pods/finalizers
  verbs:
  - update
- apiGroups:
  - resource.k8s.io
  resources:
  - resourceclaims
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - resource.k8s.io
  resources:
  - resourceclaims
  - resourceclaims/status
  verbs:
  - patch
  - update
- apiGroups:
  - ''
  resources:
  - pods/status
  verbs:
  - patch
  - update
- apiGroups:
  - ''
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
  - update
