apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:pod-garbage-collector
rules:
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - delete
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - pods/status
  verbs:
  - patch
