apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    k8s-app: metrics-server
    objectset.rio.cattle.io/hash: 9a6f488150c249811b9df07e116280789628963e
  name: system:metrics-server
rules:
- apiGroups:
  - ''
  resources:
  - nodes/metrics
  verbs:
  - get
- apiGroups:
  - ''
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
