apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:kube-aggregator
rules:
- apiGroups:
  - ''
  resources:
  - endpoints
  - services
  verbs:
  - get
  - list
  - watch
