apiVersion: v1
kind: Service
metadata:
  name: recipelab-redis
  namespace: recipelab
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: recipelab-redis
