apiVersion: v1
kind: Service
metadata:
  name: recipelab-postgres
  namespace: recipelab
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    app: recipelab-postgres
