apiVersion: v1
kind: Service
metadata:
  name: recipelab-api
  namespace: recipelab
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: recipelab-api
