apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipelab-backups-pvc
  namespace: recipelab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
