apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:euXyDbI=,iv:xW2qOVhAXlqAhZB4HfQ2HEBtkuZO9vB/lbcMaa99Rzw=,tag:oFx//4jngjsIQAANko1T/w==,type:str]
    admin-password: ENC[AES256_GCM,data:tK6skVPVcnc=,iv:/wruM9fmSsrXcmx3WrzLMbgsG9wRQwet+/MtKFl56zQ=,tag:Efw5NdunSLP9wFtW0KE8vA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r2un9h6vv43hqd089mfaxks90z4s30hakru54pfsdctclnppwdhs53g6ar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIb2ZIcUFtcmlMQVFXaFBv
            eFFqWnZCUkhUVmlPZmVtYjR0Z2hTN0NZelNVCjNWK1NYWHVXTXdzYnBuM2RWMnBB
            eE03SWhZT3AxTWo5Vld3dWZPVGJmRFkKLS0tIHFnQnVwc2V5RTJrNE9NbExTeExQ
            VnpMbXZzd3J4K3BXWVoyOG5ySU9Ra0kKi1v9mknLXCgdEmgWGbL2RoDFc2krxNgQ
            E2KqM7AJVGZu8VFfODwF/axVqfWWmo620f1Ht+r3KzYYDoEjN3kAZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T17:28:30Z"
    mac: ENC[AES256_GCM,data:qqF3e+f6esj1pCFmy9NfsEi0qJVlr3Wfr4jW18j9Ujqq24/EWx/kwGCAJnHCzLKWLko7thLRkQ9d5ijWsLl67gpyziU0CmBqnvWJW+YukteoWI1mle4MlobnxXr3YLO5jyWQ7u3zt+5pqO8DRL4UWuBFjqS6aNz9ZqbFLIEU1aE=,iv:1O4UKt8A9cqslY/XBc1GYyi66duuN4Gh+j3JwD9XklE=,tag:6A7NbWsBD1b3DTeyBUpvrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
